# Generated by Django 5.0.4 on 2024-05-04 20:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Telephone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_prod', models.CharField(max_length=100)),
                ('Prix', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('Image', models.ImageField(upload_to='uploads/product/')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Piecesstore.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Address', models.CharField(blank=True, default='', max_length=100)),
                ('Telephone', models.CharField(blank=True, default='', max_length=20)),
                ('Date', models.DateField(default=datetime.datetime.today)),
                ('Status', models.BooleanField(default=False)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Piecesstore.customer')),
                ('Produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Piecesstore.product')),
            ],
        ),
    ]
