# Generated by Django 5.0.6 on 2024-05-23 23:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piecesstore', '0003_remove_order_address_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Piecesstore.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='Date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='Produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Piecesstore.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Piecesstore.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='order',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
